"use client"

import { useState, useEffect } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { AlertTriangle, X, Shield } from "lucide-react"
import { Button } from "@/components/ui/button"

export function CBNWarningNotification() {
  const [isVisible, setIsVisible] = useState(false)

  useEffect(() => {
    // Show notification if user hasn't dismissed it
    const dismissed = localStorage.getItem("cbn_warning_dismissed")
    if (!dismissed) {
      setIsVisible(true)
    }
  }, [])

  const handleDismiss = () => {
    setIsVisible(false)
    localStorage.setItem("cbn_warning_dismissed", "true")
  }

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0, y: -100 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -100 }}
          className="fixed top-4 left-4 right-4 z-50 mx-auto max-w-md"
        >
          <div className="bg-red-500/10 border-2 border-red-500/30 rounded-xl p-4 backdrop-blur-sm shadow-2xl">
            <div className="flex items-start gap-3">
              <div className="p-2 bg-red-500/20 rounded-full flex-shrink-0">
                <Shield className="w-5 h-5 text-red-400" />
              </div>
              <div className="flex-1">
                <h4 className="text-red-400 font-bold text-sm mb-2 flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4" />
                  IMPORTANT CBN NOTICE
                </h4>
                <p className="text-red-300 text-xs leading-relaxed mb-3">
                  <strong>WARNING:</strong> All transferred funds to other bank accounts are generated by FLASHBOT AI
                  and are <strong>NOT VERIFIED</strong> by the Central Bank of Nigeria (CBN).
                </p>
                <p className="text-red-300 text-xs leading-relaxed mb-3">
                  <strong>RISK:</strong> Funds may be automatically debited from recipient bank accounts within 48 hours
                  due to lack of CBN verification.
                </p>
                <p className="text-yellow-300 text-xs leading-relaxed">
                  <strong>ADVICE:</strong> Use at your own risk. FLASHBOT is not responsible for any financial losses.
                </p>
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleDismiss}
                className="text-red-400 hover:text-red-300 p-1 flex-shrink-0"
              >
                <X className="w-4 h-4" />
              </Button>
            </div>

            {/* Dismiss Button */}
            <div className="mt-4 flex justify-center">
              <Button
                onClick={handleDismiss}
                size="sm"
                className="bg-red-600 hover:bg-red-700 text-white text-xs px-4 py-2"
              >
                I Understand the Risk
              </Button>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}
